# -*- coding: utf-8 -*-
"""EfficientSU2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zC3eSABiCXNyF7NthANWtFwfeuLKR2_w
"""

!pip install cirq numpy

import cirq
import numpy as np

class EfficientSU2:

    def __init__(self,
                 n_qubits=4,
                 reps=2):

        self.n_qubits = n_qubits
        self.reps = reps

        self.qubits = cirq.LineQubit.range(n_qubits)


    def build_circuit(self, theta):

        circuit = cirq.Circuit()

        parameter_index = 0


        for layer in range(self.reps):

          #single qubit rotations
            for q in self.qubits:

                ry_angle = theta[parameter_index]
                rz_angle = theta[parameter_index + 1]

                parameter_index += 2


                circuit.append(
                    cirq.ry(ry_angle)(q)
                )

                circuit.append(
                    cirq.rz(rz_angle)(q)
                )

                #entanglement
            for i in range(self.n_qubits - 1):

                circuit.append(
                    cirq.CNOT(
                        self.qubits[i],
                        self.qubits[i+1]
                    )
                )


        return circuit

#create 4 qubit circuit
n_qubits = 4

ansatz = EfficientSU2(
    n_qubits=4,
    reps=2
)

theta = np.random.random(16)
circuit = ansatz.build_circuit(theta)

print(circuit)