# -*- coding: utf-8 -*-
"""UCCSD_ansatz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k6hKZCeW9DXsWml61EA275nMRtpZAhIy
"""

#imports
!pip uninstall -y numpy
!pip install "numpy<2"
!pip install --upgrade cirq cirq-google
!pip install openfermion
!pip install openfermionpyscf
!pip install pyscf
!pip install scipy

import numpy as np
import math
import scipy
import random
import matplotlib.pyplot as plt
import numpy as np
import cirq

from scipy.linalg import expm

from openfermion import (
    FermionOperator,
    jordan_wigner
)

from openfermion.linalg import get_sparse_operator

try:
    import cirq
except ImportError:
    print("installing cirq...")
    !pip install cirq --quiet
    import cirq
    print("installed cirq.")


import warnings
warnings.filterwarnings("ignore")

print("Libraries Imported Successfully")

theta1 = 0.12
theta2 = 0.05

n_qubits = 4
qubits = cirq.LineQubit.range(n_qubits)

single = FermionOperator("2^ 0", theta1) - FermionOperator("0^ 2", theta1)

double = (
    FermionOperator("2^ 3^ 1 0", theta2)
    - FermionOperator("0^ 1^ 3 2", theta2)
)

cluster = single + double

qubit_op = jordan_wigner(cluster)

U = expm(get_sparse_operator(qubit_op).toarray())

ucc_gate = cirq.MatrixGate(U)

import numpy as np
import cirq

from scipy.linalg import expm

from openfermion import (
    FermionOperator,
    jordan_wigner
)

from openfermion.linalg import get_sparse_operator


class UCCSDAnsatz:

    def __init__(self,
                 n_qubits,
                 single_excitations,
                 double_excitations):

        self.n_qubits = n_qubits
        self.qubits = cirq.LineQubit.range(n_qubits)

        self.single_excitations = single_excitations
        self.double_excitations = double_excitations

    def build_gate(self, theta):

        cluster = FermionOperator()

        index = 0

        # Singles
        for i, a in self.single_excitations:

            t = theta[index]
            index += 1

            cluster += (
                FermionOperator(f"{a}^ {i}", t)
                - FermionOperator(f"{i}^ {a}", t)
            )

        # Doubles
        for i, j, a, b in self.double_excitations:

            t = theta[index]
            index += 1

            cluster += (
                FermionOperator(f"{a}^ {b}^ {j} {i}", t)
                - FermionOperator(f"{i}^ {j}^ {b} {a}", t)
            )

        qubit_operator = jordan_wigner(cluster)

        matrix = get_sparse_operator(
            qubit_operator,
            n_qubits=self.n_qubits
        ).toarray()

        unitary = expm(matrix)

        return cirq.MatrixGate(unitary)

    def build_circuit(self,
                      theta,
                      occupied_orbitals):

        circuit = cirq.Circuit()

        # Hartree-Fock state
        for orbital in occupied_orbitals:
            circuit.append(cirq.X(self.qubits[orbital]))
        gate = self.build_gate(theta)
        circuit.append(
            gate(*self.qubits)
        )

        return circuit