# -*- coding: utf-8 -*-
"""ADAPT_vqe_ansatz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aYs21pfJNuQabGrEEk7sbh-JO_1j4UqQ
"""

!pip install cirq openfermion scipy numpy

import cirq
import numpy as np

from scipy.linalg import expm

from openfermion import (
    FermionOperator,
    jordan_wigner
)

from openfermion.linalg import get_sparse_operator

class ADAPTVQEAnsatz:

    def __init__(
        self,
        n_qubits,
        operator_pool
    ):

        self.n_qubits = n_qubits
        self.qubits = cirq.LineQubit.range(n_qubits)

        self.operator_pool = operator_pool

        self.selected_operators = []


    # Convert fermionic operator to Cirq gate
    def operator_to_gate(
        self,
        operator,
        theta
    ):

        qubit_operator = jordan_wigner(operator)


        matrix = get_sparse_operator(
            qubit_operator,
            n_qubits=self.n_qubits
        ).toarray()


        unitary = expm(
            theta * matrix
        )


        return cirq.MatrixGate(unitary)



    # Add selected operator to ansatz
    def add_operator(
        self,
        operator_index
    ):

        self.selected_operators.append(
            self.operator_pool[operator_index]
        )



    # Build final circuit
    def build_circuit(
        self,
        theta,
        occupied_orbitals
    ):

        circuit = cirq.Circuit()


        # Hartree-Fock state
        for orbital in occupied_orbitals:

            circuit.append(
                cirq.X(
                    self.qubits[orbital]
                )
            )


        # Apply selected ADAPT operators
        for i, operator in enumerate(
            self.selected_operators
        ):

            gate = self.operator_to_gate(
                operator,
                theta[i]
            )


            circuit.append(
                gate(
                    *self.qubits
                )
            )


        return circuit

#single excitations
pool = []


pool.append(
    FermionOperator("2^ 0")
    -
    FermionOperator("0^ 2")
)


pool.append(
    FermionOperator("3^ 0")
    -
    FermionOperator("0^ 3")
)


pool.append(
    FermionOperator("2^ 1")
    -
    FermionOperator("1^ 2")
)


pool.append(
    FermionOperator("3^ 1")
    -
    FermionOperator("1^ 3")
)

#double excitaions
pool.append(
    FermionOperator("2^ 3^ 1 0")
    -
    FermionOperator("0^ 1^ 3 2")
)

adapt = ADAPTVQE(
    n_qubits=4,
    operator_pool=pool
)

def select_operator(gradients):

    return np.argmax(
        gradients
    )

    gradients = [
    0.01,
    0.25,
    0.04,
    0.03,
    0.12
]


best = select_operator(
    gradients
)


adapt.add_operator(best)

theta = np.array(
    [0.5]
)


circuit = adapt.build_circuit(
    theta,
    occupied_orbitals=[0,1]
)


print(circuit)