# -*- coding: utf-8 -*-
"""Graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PSbjCW5WE1s0wQjKxvpdc6DrQ_yZujGF
"""

#AdaptVQE ansatz

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import MultipleLocator

def run_adapt_convergence():
    convergence_data = {}
    initial_guess = np.full(num_adapt_parameters, 0.01)

    # 1. COBYLA
    energies = []
    def cost(x):
        e = expectation_value_adapt(x)
        energies.append(e)
        return e
    minimize(cost, initial_guess, method='COBYLA')
    convergence_data['COBYLA'] = energies

    # 2. SLSQP
    energies = []
    def cost(x):
        e = expectation_value_adapt(x)
        energies.append(e)
        return e
    minimize(cost, initial_guess, method='SLSQP')
    convergence_data['SLSQP'] = energies

    # 3. Nelder-Mead
    energies = []
    def cost(x):
        e = expectation_value_adapt(x)
        energies.append(e)
        return e
    minimize(cost, initial_guess, method='Nelder-Mead')
    convergence_data['Nelder-Mead'] = energies

    # 4. SPSA
    energies = []
    def cost(x):
        e = expectation_value_adapt(x)
        energies.append(e)
        return e
    spsa.minimize(cost, initial_guess, iterations=100)
    convergence_data['SPSA'] = energies

    # 5. EPO
    problem_dict = {
        "bounds": [FloatVar(lb=-math.pi, ub=math.pi) for _ in range(num_adapt_parameters)],
        "obj_func": expectation_value_adapt,
        "minmax": "min",
        "verbose": False,
        "log_to": "None"
    }
    optimizer = EPC.DevEPC(epoch=50, pop_size=5)
    optimizer.solve(problem_dict)
    convergence_data['EPO'] = optimizer.history.list_global_best_fit

    return convergence_data

print("Collecting ADAPT-VQE convergence data...")
adapt_conv_results = run_adapt_convergence()

# Plotting
fig, ax = plt.subplots(figsize=(12, 7))
for label, data in adapt_conv_results.items():
    ax.plot(data, label=label)

ax.axhline(y=theoretical_energy, color='r', linestyle='--', label='Theoretical Ground State')
ax.xaxis.set_major_locator(MultipleLocator(50))
ax.set_xlabel('Evaluation Count')
ax.set_ylabel('Energy (Hartrees)')
ax.set_title('Energy Convergence Comparison: ADAPT-VQE (Jordan-Wigner Mapping)')
ax.legend()
ax.grid(True, which='both', linestyle='--', alpha=0.5)
plt.show()

# Margin of Error
print("\n--- ADAPT-VQE Margin of Error ---")
for name, data in adapt_conv_results.items():
    final_e = data[-1]
    error = abs(final_e - theoretical_energy)
    print(f"{name:12}: Final Energy = {final_e:.8f} Hartrees | Error = {error:.8e} Hartrees")

#EfficientSU2
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import MultipleLocator

def run_su2_convergence():
    convergence_data = {}
    # Start with a small non-zero guess for all 16 parameters
    initial_guess = np.full(num_su2_parameters, 0.01)

    # 1. COBYLA
    energies = []
    def cost_cobyla(x):
        e = expectation_value_su2(x)
        energies.append(e)
        return e
    minimize(cost_cobyla, initial_guess, method='COBYLA', bounds=su2_bounds)
    convergence_data['COBYLA'] = energies

    # 2. SLSQP
    energies = []
    def cost_slsqp(x):
        e = expectation_value_su2(x)
        energies.append(e)
        return e
    minimize(cost_slsqp, initial_guess, method='SLSQP', bounds=su2_bounds)
    convergence_data['SLSQP'] = energies

    # 3. Nelder-Mead
    energies = []
    def cost_nm(x):
        e = expectation_value_su2(x)
        energies.append(e)
        return e
    minimize(cost_nm, initial_guess, method='Nelder-Mead', bounds=su2_bounds)
    convergence_data['Nelder-Mead'] = energies

    # 4. SPSA
    energies = []
    def cost_spsa(x):
        e = expectation_value_su2(x)
        energies.append(e)
        return e
    try:
        spsa.minimize(cost_spsa, initial_guess, iterations=100)
    except Exception:
        pass # SPSA often overflows on SU2 due to 16 parameters
    convergence_data['SPSA'] = energies

    # 5. EPO
    problem_dict = {
        "bounds": [FloatVar(lb=-np.pi, ub=np.pi) for _ in range(num_su2_parameters)],
        "obj_func": expectation_value_su2,
        "minmax": "min",
        "verbose": False,
        "log_to": "None"
    }
    optimizer = EPC.DevEPC(epoch=50, pop_size=5)
    optimizer.solve(problem_dict)
    convergence_data['EPO'] = optimizer.history.list_global_best_fit

    return convergence_data

print("Collecting EfficientSU2 convergence data (16 parameters)... This may take a moment.")
su2_conv_results = run_su2_convergence()

# Plotting
fig, ax = plt.subplots(figsize=(12, 7))
for label, data in su2_conv_results.items():
    if data:
        ax.plot(data, label=label)

ax.axhline(y=theoretical_energy, color='r', linestyle='--', label='Theoretical Ground State')

# Formatting X-axis: 0 to 900 with increments of 50
ax.set_xlim(0, 900)
ax.xaxis.set_major_locator(MultipleLocator(50))

ax.set_xlabel('Evaluation Count')
ax.set_ylabel('Energy (Hartrees)')
ax.set_title('Energy Convergence Comparison: EfficientSU2 (Jordan-Wigner Mapping)')
ax.legend()
ax.grid(True, which='both', linestyle='--', alpha=0.5)
plt.show()

# Margin of Error Calculation
print("\n--- EfficientSU2 Margin of Error ---")
for name, data in su2_conv_results.items():
    if data:
        final_e = data[-1]
        error = abs(final_e - theoretical_energy)
        print(f"{name:12}: Final Energy = {final_e:.8f} Hartrees | Error = {error:.8e} Hartrees")
    else:
        print(f"{name:12}: Failed to converge (Check for overflows)")

#uccsd

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import MultipleLocator

# Theoretical ground state energy for H2 at 0.74A (STO-3G)
theoretical_energy = -1.13728383

def run_uccsd_convergence():
    convergence_data = {}

    # 1. COBYLA
    cobyla_energies = []
    def cost_cobyla(x):
        e = expectation_value_uccsd_fast(x)
        cobyla_energies.append(e)
        return e
    minimize(cost_cobyla, np.zeros(num_uccsd_parameters), method='COBYLA')
    convergence_data['COBYLA'] = cobyla_energies

    # 2. SLSQP
    slsqp_energies = []
    def cost_slsqp(x):
        e = expectation_value_uccsd_fast(x)
        slsqp_energies.append(e)
        return e
    minimize(cost_slsqp, np.zeros(num_uccsd_parameters), method='SLSQP')
    convergence_data['SLSQP'] = slsqp_energies

    # 3. Nelder-Mead
    nm_energies = []
    def cost_nm(x):
        e = expectation_value_uccsd_fast(x)
        nm_energies.append(e)
        return e
    minimize(cost_nm, np.full(num_uccsd_parameters, 0.01), method='Nelder-Mead')
    convergence_data['Nelder-Mead'] = nm_energies

    # 4. SPSA
    spsa_energies = []
    def cost_spsa(x):
        e = expectation_value_uccsd_fast(x)
        spsa_energies.append(e)
        return e
    spsa.minimize(cost_spsa, np.full(num_uccsd_parameters, 0.01), iterations=100)
    convergence_data['SPSA'] = spsa_energies

    # 5. EPO (mealpy)
    problem_dict = {
        "bounds": [FloatVar(lb=-math.pi, ub=math.pi) for _ in range(num_uccsd_parameters)],
        "obj_func": expectation_value_uccsd_fast,
        "minmax": "min",
        "verbose": False,
        "log_to": "None"
    }
    optimizer = EPC.DevEPC(epoch=100, pop_size=5)
    best_agent = optimizer.solve(problem_dict)
    convergence_data['EPO'] = optimizer.history.list_global_best_fit

    return convergence_data

print("Collecting convergence data...")
conv_results = run_uccsd_convergence()

# Plotting
fig, ax = plt.subplots(figsize=(12, 7))
for label, data in conv_results.items():
    ax.plot(data, label=label)

ax.axhline(y=theoretical_energy, color='r', linestyle='--', label='Theoretical Ground State')

# Formatting X-axis: increments of 50
ax.xaxis.set_major_locator(MultipleLocator(50))

ax.set_xlabel('Evaluation Count')
ax.set_ylabel('Energy (Hartrees)')
ax.set_title('Energy Convergence Comparison: UCCSD Ansatz (Jordan-Wigner Mapping)')
ax.legend()
ax.grid(True, which='both', linestyle='--', alpha=0.5)
plt.show()

# Margin of Error Calculation
print("\n--- Margin of Error (Final Result vs Theoretical Ground State) ---")
for name, data in conv_results.items():
    final_e = data[-1]
    error = abs(final_e - theoretical_energy)
    print(f"{name:12}: Final Energy = {final_e:.8f} Hartrees | Error = {error:.8e} Hartrees")